# Generated by Django 4.2.30 on 2026-07-05 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vj_startups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='invited_emails',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='wing',
            name='wing_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_wings', to=settings.AUTH_USER_MODEL),
        ),
    ]
