# Generated by Django 4.2.30 on 2026-07-05 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vj_startups', '0002_startup_invited_emails_wing_wing_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='vjprojectextension',
            name='wing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='vj_startups.wing'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='public_visibility',
            field=models.BooleanField(default=False),
        ),
    ]
