# Generated by Django 4.2.30 on 2026-07-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vj_startups', '0003_vjprojectextension_wing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vjissueextension',
            name='last_reminder_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vjissueextension',
            name='reminder_frequency_hours',
            field=models.IntegerField(default=0),
        ),
    ]
