# Generated by Django 4.2.30 on 2026-07-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vj_startups', '0004_vjissueextension_last_reminder_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wing',
            name='invited_emails',
            field=models.JSONField(default=list),
        ),
    ]
