# Generated by Django 4.2.30 on 2026-08-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vj_startups', '0006_organizationmemberprofile_is_club_member_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmemberprofile',
            name='role',
            field=models.CharField(default='Member', max_length=255),
        ),
    ]
