# Generated by Django 4.2.30 on 2026-09-20 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vj_startups', '0007_organizationmemberprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmemberprofile',
            name='public_admin_token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='organizationmemberprofile',
            name='public_admin_token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationmemberprofile',
            name='public_role',
            field=models.CharField(choices=[('USER', 'User'), ('STUDENT', 'Student'), ('WING_MEMBER', 'Wing Member'), ('WING_MASTER', 'Wing Master'), ('ADMIN', 'Admin')], default='STUDENT', max_length=20),
        ),
        migrations.AddField(
            model_name='organizationmemberprofile',
            name='public_session_token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='organizationmemberprofile',
            name='public_session_token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='annual_growth_rate',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='startup',
            name='business_model',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='competitive_advantage',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='customers',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='startup',
            name='financial_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='founders_text',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='startup',
            name='funding_status',
            field=models.CharField(blank=True, choices=[('BOOTSTRAPPED', 'Bootstrapped'), ('SEEKING_FUNDING', 'Seeking Funding'), ('PRE_SEED', 'Pre-Seed'), ('SEED', 'Seed'), ('SERIES_A', 'Series A'), ('LATER_STAGE', 'Later Stage')], max_length=30),
        ),
        migrations.AddField(
            model_name='startup',
            name='incorporation_status',
            field=models.CharField(blank=True, choices=[('NOT_INCORPORATED', 'Not Incorporated'), ('INCORPORATED', 'Incorporated'), ('LLC', 'LLC'), ('PARTNERSHIP', 'Partnership'), ('OTHER', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='startup',
            name='key_features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='startup',
            name='market_size',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='startup',
            name='markets',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='startup',
            name='related_idea_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='target_audience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='target_users',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='technology_stack',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='startup',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='startup',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='StartupTeamMember',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('avatar', models.URLField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='vj_startups.startup')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Startup Team Member',
                'verbose_name_plural': 'Startup Team Members',
                'db_table': 'vj_startup_team_members',
            },
        ),
        migrations.CreateModel(
            name='StartupSupportProgram',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('program', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_programs', to='vj_startups.startup')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Startup Support Program',
                'verbose_name_plural': 'Startup Support Programs',
                'db_table': 'vj_startup_support_programs',
            },
        ),
    ]
