# Generated by Django 4.2.30 on 2026-09-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vj_startups', '0008_organizationmemberprofile_public_admin_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='cover_image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='one_pager_url',
            field=models.URLField(blank=True),
        ),
    ]
