# Generated by Django 4.2.30 on 2026-09-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vj_startups', '0009_startup_cover_image_startup_one_pager_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='related_idea_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
