# Generated by Django 4.2.30 on 2026-09-20 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vj_startups', '0010_alter_startup_related_idea_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemstatement',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='problemstatement',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='solutionproposal',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='solutionproposal',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='solutionproposal',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='Opportunity',
        ),
        migrations.DeleteModel(
            name='ProblemStatement',
        ),
        migrations.DeleteModel(
            name='SolutionProposal',
        ),
    ]
