# Generated by Django 4.2.30 on 2026-09-22 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vj_startups', '0011_remove_problemstatement_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vjissueextension',
            name='evidence_url',
        ),
        migrations.RemoveField(
            model_name='vjissueextension',
            name='impact_metric',
        ),
        migrations.RemoveField(
            model_name='vjissueextension',
            name='last_reminder_sent',
        ),
        migrations.RemoveField(
            model_name='vjissueextension',
            name='reminder_frequency_hours',
        ),
        migrations.RemoveField(
            model_name='vjissueextension',
            name='review_status',
        ),
        migrations.RemoveField(
            model_name='vjissueextension',
            name='reviewed_by',
        ),
    ]
