-- Backend 2 (VJ Startups Express service) table bootstrap for a FRESH production
-- Postgres database that already has Django's `plane` schema applied (i.e. run
-- `python manage.py migrate` FIRST - this script assumes the "users" table
-- already exists and is Django-owned).
--
-- Do NOT run `npx prisma migrate deploy` or `npx prisma db push` in production.
-- See docs/vj-startups/production_db_merge_runbook.md for why: the migration
-- files under backend/prisma/migrations are stale (the init migration still
-- contains `CREATE TABLE "users"` and legacy `startups`/`projects`/`tasks`
-- tables from before the schema was consolidated onto Plane's database, and
-- would either collide with Django's real `users` table or silently diff
-- against it). This script was generated by reading the ACTUAL live schema of
-- a working local dev database on 2026-09-21 - it creates exactly, and only,
-- the tables backend 2 genuinely still owns and queries (confirmed against
-- APIs/*.js), with the verified/verifiedBy/verifiedAt/verificationNotes
-- columns already folded into problems/ideas rather than left as a
-- separate ALTER step.
--
-- Safe to run once against an empty production database, inside a transaction.
-- Re-running against a database that already has these tables will fail loudly
-- (relation already exists) rather than silently altering anything - that's
-- intentional.

BEGIN;

-- ============================================================================
-- ENUM TYPES (only the ones actually referenced by tables below)
-- ============================================================================
CREATE TYPE "worthiness_level" AS ENUM ('HIGH', 'MEDIUM', 'LOW');
CREATE TYPE "access_level" AS ENUM ('PUBLIC', 'PRIVATE');
CREATE TYPE "questionnaire_status" AS ENUM ('DRAFT', 'COMPLETED');
CREATE TYPE "stage_type" AS ENUM ('PROBLEM', 'IDEA', 'STARTUP');

-- ============================================================================
-- PROBLEMS
-- ============================================================================
CREATE TABLE "problems" (
    "id" TEXT NOT NULL,
    "problemId" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "briefparagraph" TEXT NOT NULL,
    "description" TEXT,
    "marketSize" TEXT,
    "existingSolutions" TEXT,
    "currentGaps" TEXT,
    "targetCustomers" TEXT,
    "image" TEXT,
    "upvotes" INTEGER NOT NULL DEFAULT 0,
    "background" TEXT,
    "scalability" TEXT,
    "addedByName" TEXT NOT NULL,
    "addedByEmail" TEXT NOT NULL,
    "tags" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "verified" BOOLEAN NOT NULL DEFAULT false,
    "verifiedBy" TEXT,
    "verifiedAt" TIMESTAMP(3),
    "verificationNotes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "problems_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "problem_collaborators" (
    "id" TEXT NOT NULL,
    "problemId" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "problem_collaborators_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "problem_upvotes" (
    "id" TEXT NOT NULL,
    "problemId" TEXT NOT NULL,
    "userEmail" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "problem_upvotes_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "problem_comments" (
    "id" TEXT NOT NULL,
    "commentId" TEXT NOT NULL,
    "problemId" TEXT NOT NULL,
    "text" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "likes" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "problem_comments_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "problem_comment_likes" (
    "id" TEXT NOT NULL,
    "commentId" TEXT NOT NULL,
    "userEmail" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "problem_comment_likes_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "problem_comment_replies" (
    "id" TEXT NOT NULL,
    "replyId" TEXT NOT NULL,
    "commentId" TEXT NOT NULL,
    "text" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "likes" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "problem_comment_replies_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "problem_reply_likes" (
    "id" TEXT NOT NULL,
    "replyId" TEXT NOT NULL,
    "userEmail" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "problem_reply_likes_pkey" PRIMARY KEY ("id")
);

-- ============================================================================
-- IDEAS
-- ============================================================================
CREATE TABLE "ideas" (
    "id" TEXT NOT NULL,
    "ideaId" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "titleImage" TEXT,
    "relatedProblemId" TEXT,
    "stage" INTEGER NOT NULL DEFAULT 1,
    "upvotes" INTEGER NOT NULL DEFAULT 0,
    "mentor" TEXT,
    "contact" TEXT,
    "addedByName" TEXT NOT NULL,
    "addedByEmail" TEXT NOT NULL,
    "tags" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "targetCustomers" TEXT,
    "verified" BOOLEAN NOT NULL DEFAULT false,
    "verifiedBy" TEXT,
    "verifiedAt" TIMESTAMP(3),
    "verificationNotes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "isStartupWorthy" BOOLEAN NOT NULL DEFAULT false,
    "worthinessLevel" "worthiness_level",
    "evaluatedAt" TIMESTAMP(3),
    "hasStartupCreated" BOOLEAN NOT NULL DEFAULT false,
    CONSTRAINT "ideas_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "idea_collaborators" (
    "id" TEXT NOT NULL,
    "ideaId" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "idea_collaborators_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "idea_team_members" (
    "id" TEXT NOT NULL,
    "ideaId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "email" TEXT,
    "role" TEXT NOT NULL,
    "image" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "idea_team_members_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "idea_upvotes" (
    "id" TEXT NOT NULL,
    "ideaId" TEXT NOT NULL,
    "userEmail" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "idea_upvotes_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "idea_comments" (
    "id" TEXT NOT NULL,
    "commentId" TEXT NOT NULL,
    "ideaId" TEXT NOT NULL,
    "author" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "idea_comments_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "idea_comment_likes" (
    "id" TEXT NOT NULL,
    "commentId" TEXT NOT NULL,
    "userEmail" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "idea_comment_likes_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "idea_comment_replies" (
    "id" TEXT NOT NULL,
    "replyId" TEXT NOT NULL,
    "commentId" TEXT NOT NULL,
    "author" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "idea_comment_replies_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "idea_reply_likes" (
    "id" TEXT NOT NULL,
    "replyId" TEXT NOT NULL,
    "userEmail" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "idea_reply_likes_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "idea_attachments" (
    "id" TEXT NOT NULL,
    "ideaId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "url" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "size" TEXT NOT NULL,
    "accessLevel" "access_level" NOT NULL DEFAULT 'PUBLIC',
    "uploadedBy" TEXT NOT NULL,
    "uploadedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "idea_attachments_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "idea_links" (
    "id" TEXT NOT NULL,
    "ideaId" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "url" TEXT NOT NULL,
    "description" TEXT,
    "accessLevel" "access_level" NOT NULL DEFAULT 'PUBLIC',
    "addedBy" TEXT NOT NULL,
    "addedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "idea_links_pkey" PRIMARY KEY ("id")
);

-- ============================================================================
-- QUESTIONNAIRE (TRL evaluations)
-- ============================================================================
CREATE TABLE "questionnaire_responses" (
    "id" TEXT NOT NULL,
    "responseId" TEXT NOT NULL,
    "userId" TEXT,
    "userEmail" TEXT NOT NULL,
    "userName" TEXT,
    "ideaId" TEXT NOT NULL,
    "stageFrom" INTEGER NOT NULL,
    "stageTo" INTEGER NOT NULL,
    "responses" JSONB NOT NULL,
    "overallScore" INTEGER,
    "status" "questionnaire_status" NOT NULL DEFAULT 'DRAFT',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "questionnaire_responses_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "questionnaire_scores" (
    "id" TEXT NOT NULL,
    "questionnaireId" TEXT NOT NULL,
    "problemClarity" INTEGER,
    "marketPotential" INTEGER,
    "solutionViability" INTEGER,
    "competitivePosition" INTEGER,
    "executionReadiness" INTEGER,
    CONSTRAINT "questionnaire_scores_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "questionnaire_recommendations" (
    "id" TEXT NOT NULL,
    "questionnaireId" TEXT NOT NULL,
    "recommendation" TEXT NOT NULL,
    CONSTRAINT "questionnaire_recommendations_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "questionnaire_criteria" (
    "id" TEXT NOT NULL,
    "questionnaireId" TEXT NOT NULL,
    "revenueModelValidated" BOOLEAN NOT NULL DEFAULT false,
    "customerWillingnessToPay" BOOLEAN NOT NULL DEFAULT false,
    "marketValidation" BOOLEAN NOT NULL DEFAULT false,
    "revenueGenerated" BOOLEAN NOT NULL DEFAULT false,
    "technicalReadiness" BOOLEAN NOT NULL DEFAULT false,
    "customerBase" BOOLEAN NOT NULL DEFAULT false,
    "scalabilityPlan" BOOLEAN NOT NULL DEFAULT false,
    "metCriteria" INTEGER NOT NULL DEFAULT 0,
    "totalCriteria" INTEGER NOT NULL DEFAULT 7,
    "isStartupWorthy" BOOLEAN NOT NULL DEFAULT false,
    "worthinessLevel" "worthiness_level",
    CONSTRAINT "questionnaire_criteria_pkey" PRIMARY KEY ("id")
);

-- ============================================================================
-- ANNOUNCEMENTS & STAGE NOTIFICATIONS
-- ============================================================================
CREATE TABLE "announcements" (
    "id" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "postedByName" TEXT NOT NULL,
    "postedByEmail" TEXT NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "announcements_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "stage_notifications" (
    "id" TEXT NOT NULL,
    "ideaId" TEXT NOT NULL,
    "ideaTitle" TEXT NOT NULL,
    "userEmail" TEXT NOT NULL,
    "userName" TEXT,
    "userAvatar" TEXT,
    "previousStage" INTEGER NOT NULL,
    "newStage" INTEGER NOT NULL,
    "stageName" TEXT NOT NULL,
    "stageType" "stage_type" NOT NULL DEFAULT 'IDEA',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expiresAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "stage_notifications_pkey" PRIMARY KEY ("id")
);

-- ============================================================================
-- INDEXES
-- ============================================================================
CREATE UNIQUE INDEX "problems_problemId_key" ON "problems"("problemId");
CREATE INDEX "problems_problemId_idx" ON "problems"("problemId");
CREATE INDEX "problems_addedByEmail_idx" ON "problems"("addedByEmail");
CREATE INDEX "problems_createdAt_idx" ON "problems"("createdAt");
CREATE INDEX "problems_verified_idx" ON "problems"("verified");

CREATE INDEX "problem_collaborators_problemId_idx" ON "problem_collaborators"("problemId");
CREATE INDEX "problem_collaborators_email_idx" ON "problem_collaborators"("email");
CREATE UNIQUE INDEX "problem_collaborators_problemId_email_key" ON "problem_collaborators"("problemId", "email");

CREATE INDEX "problem_upvotes_problemId_idx" ON "problem_upvotes"("problemId");
CREATE INDEX "problem_upvotes_userEmail_idx" ON "problem_upvotes"("userEmail");
CREATE UNIQUE INDEX "problem_upvotes_problemId_userEmail_key" ON "problem_upvotes"("problemId", "userEmail");

CREATE UNIQUE INDEX "problem_comments_commentId_key" ON "problem_comments"("commentId");
CREATE INDEX "problem_comments_problemId_idx" ON "problem_comments"("problemId");
CREATE INDEX "problem_comments_email_idx" ON "problem_comments"("email");
CREATE INDEX "problem_comments_createdAt_idx" ON "problem_comments"("createdAt");

CREATE INDEX "problem_comment_likes_commentId_idx" ON "problem_comment_likes"("commentId");
CREATE UNIQUE INDEX "problem_comment_likes_commentId_userEmail_key" ON "problem_comment_likes"("commentId", "userEmail");

CREATE UNIQUE INDEX "problem_comment_replies_replyId_key" ON "problem_comment_replies"("replyId");
CREATE INDEX "problem_comment_replies_commentId_idx" ON "problem_comment_replies"("commentId");
CREATE INDEX "problem_comment_replies_createdAt_idx" ON "problem_comment_replies"("createdAt");

CREATE INDEX "problem_reply_likes_replyId_idx" ON "problem_reply_likes"("replyId");
CREATE UNIQUE INDEX "problem_reply_likes_replyId_userEmail_key" ON "problem_reply_likes"("replyId", "userEmail");

CREATE UNIQUE INDEX "ideas_ideaId_key" ON "ideas"("ideaId");
CREATE INDEX "ideas_ideaId_idx" ON "ideas"("ideaId");
CREATE INDEX "ideas_addedByEmail_idx" ON "ideas"("addedByEmail");
CREATE INDEX "ideas_relatedProblemId_idx" ON "ideas"("relatedProblemId");
CREATE INDEX "ideas_stage_idx" ON "ideas"("stage");
CREATE INDEX "ideas_createdAt_idx" ON "ideas"("createdAt");
CREATE INDEX "ideas_verified_idx" ON "ideas"("verified");

CREATE INDEX "idea_collaborators_ideaId_idx" ON "idea_collaborators"("ideaId");
CREATE INDEX "idea_collaborators_email_idx" ON "idea_collaborators"("email");
CREATE UNIQUE INDEX "idea_collaborators_ideaId_email_key" ON "idea_collaborators"("ideaId", "email");

CREATE INDEX "idea_team_members_ideaId_idx" ON "idea_team_members"("ideaId");

CREATE INDEX "idea_upvotes_ideaId_idx" ON "idea_upvotes"("ideaId");
CREATE INDEX "idea_upvotes_userEmail_idx" ON "idea_upvotes"("userEmail");
CREATE UNIQUE INDEX "idea_upvotes_ideaId_userEmail_key" ON "idea_upvotes"("ideaId", "userEmail");

CREATE UNIQUE INDEX "idea_comments_commentId_key" ON "idea_comments"("commentId");
CREATE INDEX "idea_comments_ideaId_idx" ON "idea_comments"("ideaId");
CREATE INDEX "idea_comments_email_idx" ON "idea_comments"("email");
CREATE INDEX "idea_comments_createdAt_idx" ON "idea_comments"("createdAt");

CREATE INDEX "idea_comment_likes_commentId_idx" ON "idea_comment_likes"("commentId");
CREATE UNIQUE INDEX "idea_comment_likes_commentId_userEmail_key" ON "idea_comment_likes"("commentId", "userEmail");

CREATE UNIQUE INDEX "idea_comment_replies_replyId_key" ON "idea_comment_replies"("replyId");
CREATE INDEX "idea_comment_replies_commentId_idx" ON "idea_comment_replies"("commentId");
CREATE INDEX "idea_comment_replies_createdAt_idx" ON "idea_comment_replies"("createdAt");

CREATE INDEX "idea_reply_likes_replyId_idx" ON "idea_reply_likes"("replyId");
CREATE UNIQUE INDEX "idea_reply_likes_replyId_userEmail_key" ON "idea_reply_likes"("replyId", "userEmail");

CREATE INDEX "idea_attachments_ideaId_idx" ON "idea_attachments"("ideaId");
CREATE INDEX "idea_attachments_accessLevel_idx" ON "idea_attachments"("accessLevel");

CREATE INDEX "idea_links_ideaId_idx" ON "idea_links"("ideaId");
CREATE INDEX "idea_links_accessLevel_idx" ON "idea_links"("accessLevel");

CREATE UNIQUE INDEX "questionnaire_responses_responseId_key" ON "questionnaire_responses"("responseId");
CREATE INDEX "questionnaire_responses_ideaId_idx" ON "questionnaire_responses"("ideaId");
CREATE INDEX "questionnaire_responses_userEmail_idx" ON "questionnaire_responses"("userEmail");
CREATE INDEX "questionnaire_responses_createdAt_idx" ON "questionnaire_responses"("createdAt");

CREATE UNIQUE INDEX "questionnaire_scores_questionnaireId_key" ON "questionnaire_scores"("questionnaireId");
CREATE INDEX "questionnaire_recommendations_questionnaireId_idx" ON "questionnaire_recommendations"("questionnaireId");
CREATE UNIQUE INDEX "questionnaire_criteria_questionnaireId_key" ON "questionnaire_criteria"("questionnaireId");

CREATE INDEX "announcements_isActive_idx" ON "announcements"("isActive");
CREATE INDEX "announcements_createdAt_idx" ON "announcements"("createdAt");

CREATE INDEX "stage_notifications_ideaId_createdAt_idx" ON "stage_notifications"("ideaId", "createdAt");
CREATE INDEX "stage_notifications_userEmail_createdAt_idx" ON "stage_notifications"("userEmail", "createdAt");
CREATE INDEX "stage_notifications_createdAt_idx" ON "stage_notifications"("createdAt");
CREATE INDEX "stage_notifications_expiresAt_idx" ON "stage_notifications"("expiresAt");

-- ============================================================================
-- FOREIGN KEYS
-- Every users(...) reference below points at Django's real, already-migrated
-- "users" table - that's the intentional cross-ORM design (see the header
-- comment in backend/prisma/schema.prisma). Do not repoint these.
-- ============================================================================
ALTER TABLE "problems" ADD CONSTRAINT "problems_addedByEmail_fkey" FOREIGN KEY ("addedByEmail") REFERENCES "users"("email") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "problem_collaborators" ADD CONSTRAINT "problem_collaborators_problemId_fkey" FOREIGN KEY ("problemId") REFERENCES "problems"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "problem_upvotes" ADD CONSTRAINT "problem_upvotes_problemId_fkey" FOREIGN KEY ("problemId") REFERENCES "problems"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "problem_upvotes" ADD CONSTRAINT "problem_upvotes_userEmail_fkey" FOREIGN KEY ("userEmail") REFERENCES "users"("email") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "problem_comments" ADD CONSTRAINT "problem_comments_problemId_fkey" FOREIGN KEY ("problemId") REFERENCES "problems"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "problem_comments" ADD CONSTRAINT "problem_comments_email_fkey" FOREIGN KEY ("email") REFERENCES "users"("email") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "problem_comment_likes" ADD CONSTRAINT "problem_comment_likes_commentId_fkey" FOREIGN KEY ("commentId") REFERENCES "problem_comments"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "problem_comment_replies" ADD CONSTRAINT "problem_comment_replies_commentId_fkey" FOREIGN KEY ("commentId") REFERENCES "problem_comments"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "problem_reply_likes" ADD CONSTRAINT "problem_reply_likes_replyId_fkey" FOREIGN KEY ("replyId") REFERENCES "problem_comment_replies"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "ideas" ADD CONSTRAINT "ideas_addedByEmail_fkey" FOREIGN KEY ("addedByEmail") REFERENCES "users"("email") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ideas" ADD CONSTRAINT "ideas_relatedProblemId_fkey" FOREIGN KEY ("relatedProblemId") REFERENCES "problems"("problemId") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "idea_collaborators" ADD CONSTRAINT "idea_collaborators_ideaId_fkey" FOREIGN KEY ("ideaId") REFERENCES "ideas"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "idea_team_members" ADD CONSTRAINT "idea_team_members_ideaId_fkey" FOREIGN KEY ("ideaId") REFERENCES "ideas"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "idea_upvotes" ADD CONSTRAINT "idea_upvotes_ideaId_fkey" FOREIGN KEY ("ideaId") REFERENCES "ideas"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "idea_upvotes" ADD CONSTRAINT "idea_upvotes_userEmail_fkey" FOREIGN KEY ("userEmail") REFERENCES "users"("email") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "idea_comments" ADD CONSTRAINT "idea_comments_ideaId_fkey" FOREIGN KEY ("ideaId") REFERENCES "ideas"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "idea_comments" ADD CONSTRAINT "idea_comments_email_fkey" FOREIGN KEY ("email") REFERENCES "users"("email") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "idea_comment_likes" ADD CONSTRAINT "idea_comment_likes_commentId_fkey" FOREIGN KEY ("commentId") REFERENCES "idea_comments"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "idea_comment_replies" ADD CONSTRAINT "idea_comment_replies_commentId_fkey" FOREIGN KEY ("commentId") REFERENCES "idea_comments"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "idea_reply_likes" ADD CONSTRAINT "idea_reply_likes_replyId_fkey" FOREIGN KEY ("replyId") REFERENCES "idea_comment_replies"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "idea_attachments" ADD CONSTRAINT "idea_attachments_ideaId_fkey" FOREIGN KEY ("ideaId") REFERENCES "ideas"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "idea_links" ADD CONSTRAINT "idea_links_ideaId_fkey" FOREIGN KEY ("ideaId") REFERENCES "ideas"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "questionnaire_responses" ADD CONSTRAINT "questionnaire_responses_ideaId_fkey" FOREIGN KEY ("ideaId") REFERENCES "ideas"("ideaId") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "questionnaire_scores" ADD CONSTRAINT "questionnaire_scores_questionnaireId_fkey" FOREIGN KEY ("questionnaireId") REFERENCES "questionnaire_responses"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "questionnaire_recommendations" ADD CONSTRAINT "questionnaire_recommendations_questionnaireId_fkey" FOREIGN KEY ("questionnaireId") REFERENCES "questionnaire_responses"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "questionnaire_criteria" ADD CONSTRAINT "questionnaire_criteria_questionnaireId_fkey" FOREIGN KEY ("questionnaireId") REFERENCES "questionnaire_responses"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "stage_notifications" ADD CONSTRAINT "stage_notifications_ideaId_fkey" FOREIGN KEY ("ideaId") REFERENCES "ideas"("ideaId") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "stage_notifications" ADD CONSTRAINT "stage_notifications_userEmail_fkey" FOREIGN KEY ("userEmail") REFERENCES "users"("email") ON DELETE RESTRICT ON UPDATE CASCADE;

COMMIT;
